name: Generate PowerPoint from Document

on:
  repository_dispatch:
    types: [generate_slides]

jobs:
  generate-slides:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (if any repository files are needed)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python (this is necessary to run the Python script)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (e.g., python-pptx, PyMuPDF, etc.)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Download the file from the URL (passed via client_payload)
      - name: Download the file from URL
        run: |
          # The file URL is passed via the client_payload of the event
          # Using curl to download the file into the 'uploads' directory
          echo "Downloading file from ${GITHUB_EVENT_CLIENT_PAYLOAD_FILE_URL}"
          curl -L -o uploads/$(basename ${{ github.event.client_payload.file_url }}) "${{ github.event.client_payload.file_url }}"
        
      # Step 5: Generate the PowerPoint Presentation using the Python script
      - name: Generate PowerPoint Presentation
        run: |
          echo "Generating PowerPoint from the uploaded file..."
          python generate_slides.py "uploads/$(basename ${{ github.event.client_payload.file_url }})" "${{ github.event.client_payload.title }}"
          
          # Check if the PowerPoint file was created successfully
          if [ ! -f "docs/output/generated-presentation.pptx" ]; then
            echo "PowerPoint generation failed: output file not found."
            exit 1
          else
            echo "PowerPoint file generated successfully."
          fi

      # Step 6: Upload the generated PowerPoint file as an artifact (optional, for easy download)
      - name: Upload PowerPoint file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: PowerPoint Presentation
          path: docs/output/generated-presentation.pptx

      # Step 7: Deploy to GitHub Pages (optional, if needed)
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_id: ${{ steps.upload-artifact.outputs.artifact_id }}
