name: Generate PowerPoint from Document

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the uploaded file (PDF or JPEG)'
        required: true
      title:
        description: 'Title of the presentation'
        required: true

jobs:
  generate-slides:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download the file from URL
        run: |
          curl -L -o uploads/$(basename ${{ github.event.inputs.file_url }}) "${{ github.event.inputs.file_url }}"

      - name: Generate PowerPoint Presentation
        run: |
          python generate_slides.py "uploads/$(basename ${{ github.event.inputs.file_url }})" "${{ github.event.inputs.title }}"

      - name: Upload PowerPoint file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: PowerPoint Presentation
          path: docs/output/
